import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { getPrice } from '@/utils/pricing';
import { toISODateString } from '@/utils/formatters';
import type { Product, CakeSize, CakeVariety, CustomerType } from '@/types';

interface OrderItemInput {
  id: string;
  size: CakeSize;
  variety: CakeVariety;
  quantity: number;
}

interface CreateOrderParams {
  customerId: string | null;
  customerName: string;
  customerType: CustomerType;
  pickupDate: Date;
  notes: string;
  items: OrderItemInput[];
  products: Product[] | undefined;
  userId: string | undefined;
}

export function useCreateOrder() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();

  return useMutation({
    mutationFn: async ({
      customerId,
      customerName,
      customerType,
      pickupDate,
      notes,
      items,
      products,
      userId,
    }: CreateOrderParams) => {
      if (!customerName.trim()) throw new Error('Please enter a customer name');

      // Calculate total
      const totalAmount = items.reduce((sum, item) => {
        return sum + getPrice(products, item.size, item.variety, customerType) * item.quantity;
      }, 0);

      // Create order - order_number is auto-generated by database trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          order_number: '', // Will be replaced by database trigger
          customer_id: customerId || null,
          customer_name: customerName,
          customer_type: customerType,
          pickup_date: toISODateString(pickupDate),
          notes: notes || null,
          total_amount: totalAmount,
          created_by: userId,
        } as any)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map((item) => {
        const product = products?.find(
          (p) => p.size === item.size && p.variety === item.variety
        );
        const unitPrice = getPrice(products, item.size, item.variety, customerType);
        
        return {
          order_id: order.id,
          product_id: product?.id || null,
          size: item.size,
          variety: item.variety,
          quantity: item.quantity,
          unit_price: unitPrice,
          total_price: unitPrice * item.quantity,
        };
      });

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      return order;
    },
    onSuccess: (order) => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard_stats'] });
      toast.success('Order created successfully!');
      navigate(`/orders/${order.id}`);
    },
    onError: (error: Error) => {
      toast.error(error.message);
    },
  });
}
